//list of action type constants

const FETCH_TRENDING_BOOKS = 'FETCH_TRENDING_BOOKS'
const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE'
const SET_IS_LOADING = 'SET_IS_LOADING'
const SET_PAGE_NUMBER = 'SET_PAGE_NUMBER'

export {
  FETCH_TRENDING_BOOKS,
  SET_SEARCH_VALUE,
  SET_IS_LOADING,
  SET_PAGE_NUMBER,
}
