//list of action type constants

const FETCH_TRENDING_BOOKS = 'FETCH_TRENDING_BOOKS';
const SEARCH_BOOKS_BY_NAME = 'SEARCH_BOOKS_BY_NAME';
const SET_IS_LOADING = 'SET_IS_LOADING';

export { FETCH_TRENDING_BOOKS, SEARCH_BOOKS_BY_NAME, SET_IS_LOADING };
