//list of action type constants

const SET_TRENDING_BOOKS = 'SET_TRENDING_BOOKS';
const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
const SET_IS_LOADING = 'SET_IS_LOADING';
const SET_PAGE_NUMBER_TRENDING = 'SET_PAGE_NUMBER_TRENDING';
const SET_SEARCHED_BOOKS = 'SET_SEARCHED_BOOKS';
const SET_PAGE_NUMBER_SEARCHING = 'SET_PAGE_NUMBER_SEARCHING';
const SET_RANDOM_BOOK = 'SET_RANDOM_BOOK';
const SET_USER_DATA = 'SET_USER_DATA';
const REMOVE_USER_DATA = 'REMOVE_USER_DATA';
const SET_TO_CART = 'SET_TO_CART';
const SET_TO_FAVORITE = 'SET_TO_FAVORITE';
const REMOVE_FROM_FAVOURITES = 'REMOVE_FROM_FAVOURITES';
const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export {
  SET_TRENDING_BOOKS,
  SET_SEARCH_VALUE,
  SET_IS_LOADING,
  SET_PAGE_NUMBER_TRENDING,
  SET_SEARCHED_BOOKS,
  SET_PAGE_NUMBER_SEARCHING,
  SET_RANDOM_BOOK,
  SET_USER_DATA,
  REMOVE_USER_DATA,
  SET_TO_CART,
  SET_TO_FAVORITE,
  REMOVE_FROM_FAVOURITES,
  REMOVE_FROM_CART,
};
