//list of action type constants

const SET_TRENDING_BOOKS = 'SET_TRENDING_BOOKS';
const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
const SET_IS_LOADING = 'SET_IS_LOADING';
const SET_PAGE_NUMBER_TRENDING = 'SET_PAGE_NUMBER_TRENDING';
const SET_SEARCHED_BOOKS = 'SET_SEARCHED_BOOKS';
const SET_PAGE_NUMBER_SEARCHING = 'SET_PAGE_NUMBER_SEARCHING';
const SET_RANDOM_BOOK = 'SET_RANDOM_BOOK'
export {
  SET_TRENDING_BOOKS,
  SET_SEARCH_VALUE,
  SET_IS_LOADING,
  SET_PAGE_NUMBER_TRENDING,
  SET_SEARCHED_BOOKS,
  SET_PAGE_NUMBER_SEARCHING,
  SET_RANDOM_BOOK
};
